### ISSUE TITLE
problem in final prediction

### ISSUE THREAD

**Issue by mskhan793** [Hostilitility/MTLF-by-tensorflow#1]
Hi,
I have been testing the algorithm with two datasets (one as a source and one as target) filled with random values. In the end, the prediction result is a straight line that is not even close to the original distribution.
Please Have a look at the code and tell me what is the issue. The code, datasets and result plot is attached.
Thank you!
[MLTF_ISSUE.zip](https://github.com/Hostilitility/MTLF-by-tensorflow/files/3841390/MLTF_ISSUE.zip)

**Comment by Hostilitility** [comment]
Is your data generated totally randomly? If so, there's not a mapping function or correlationship between features and labels and the model cannot learn anything useful to predict test data. Consequensely it would always give an average value 0.5 as its prediction.
